name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Build
      run: sbt assembly
    - name: Archive published pdfs
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: |
          target/build/spro.jar

